import type { ShaderParams } from './shaderParams';
import { Cloud, Haze, CloudLightning, Moon } from 'lucide-svelte';

export type Preset = {
    id: string;
    name: string;
    icon: any;
    params: Partial<ShaderParams>;
};

export const PRESETS: Preset[] = [
    {
        id: 'default',
        name: 'Dreamy',
        icon: Cloud,
        params: {
            bgColor: '#c7e6ff',
            lightColor1: '#d1d6e0',
            lightColor2: '#FFF0F2',
            cloudBaseCol: '#f0f6ff',
            cloudShadowCol: '#535b65',
            sunGlowCol: '#ffffff',
            sunCoreCol: '#feffc7',
            sunGlareCol: '#c3bffd',
            sunGlowPow: 100,
            sunCorePow: 36,
            sunGlarePow: 16,
            vortexSpeed: 0.1,
            vortexTwist: 0.05,
            camSpeed: 1.9,
            camFov: 1.2,
            camRollAmp: 0.2,
            camRollFreq: 0.1,
            camLookAhead: 1,
            sunPathOffset: 21,
            tunnelRadius: 2.2,
            pathAmpX: 1.4,
            pathFreqX: 0.2,
            pathAmpY: 3.8,
            pathFreqY: 0.15,
            noiseScaleBase: 0.3,
            noiseScaleDet: 0.8,
            cloudDensity: 3.8,
            drawDist: 80,
            lightningEnabled: 0,
            lightningIntensity: 1.0,
        }
    },
    {
        id: 'sunset',
        name: 'Sunset',
        icon: Haze,
        params: {
            bgColor: '#DABCCA',
            lightColor1: '#ff9900',
            lightColor2: '#E7D4CB',
            cloudBaseCol: '#ffdab9',
            cloudShadowCol: '#04052F',
            sunGlowCol: '#ffaa00',
            sunCoreCol: '#ffffcc',
            sunGlareCol: '#E2C5A7',
            cloudDensity: 3.8,
            sunCorePow: 36,
            sunGlarePow: 16,
            vortexSpeed: -0.6,
            vortexTwist: 0.2,
            camSpeed: 3.31,
            camFov: 1.82,
            camRollAmp: 0.2,
            camRollFreq: 0.1,
            camLookAhead: 1,
            sunPathOffset: 21.4,
            tunnelRadius: 2.8,
            pathAmpX: 1.4,
            pathFreqX: 0.2,
            pathAmpY: 2.99,
            pathFreqY: 0.15,
            lightningEnabled: 0,
            lightningIntensity: 0.5,
        }
    },
    {
        id: 'storm',
        name: 'Storm',
        icon: CloudLightning,
        params: {
            bgColor: '#05186B',
            lightColor1: '#B4BFCB',
            lightColor2: '#A6BACE',
            cloudBaseCol: '#4b5c74',
            cloudShadowCol: '#000000',
            sunGlowCol: '#DFE3EC',
            sunCoreCol: '#aaddff',
            sunGlareCol: '#0F2D61',
            vortexSpeed: 0.9,
            vortexTwist: -0.15,
            noiseScaleBase: 0.3,
            noiseScaleDet: 0.9,
            cloudDensity: 3.0,
            drawDist: 80,
            sunCorePow: 11,
            sunGlarePow: 16,
            lightningEnabled: 1,
            lightningChance: 0.46,
            lightningColor: '#cccbec',
            lightningIntensity: 1.4,
            lightningAudioSync: 1,
            lightningThreshold: 0.81,
        }
    },
    {
        id: 'moon',
        name: 'Moonlight',
        icon: Moon,
        params: {
            cloudBaseCol: '#a2a196',
            cloudShadowCol: '#050810',
            sunGlowCol: '#F4FFA3',
            sunCoreCol: '#FFFCE5',
            sunGlareCol: '#10337A',
            sunCorePow: 67,
            sunGlarePow: 16,
            vortexSpeed: -0.6,
            vortexTwist: 0.2,
            noiseScaleBase: 0.3,
            noiseScaleDet: 1.25,
            cloudDensity: 3.8,
            drawDist: 80,
            tunnelRadius: 2.8,
            pathAmpX: 1.4,
            pathFreqX: 0.2,
            pathAmpY: 2.99,
            pathFreqY: 0.15,
            bgColor: '#080C15',
            lightColor1: '#6B6D70',
            lightColor2: '#6b6d70',
            camSpeed: 2.5,
            camFov: 1.8,
            camRollAmp: 0.2,
            camRollFreq: 0.1,
            camLookAhead: 1,
            sunPathOffset: 30.4,
            lightningEnabled: 0,
            lightningIntensity: 0.8,
        }
    }
];

